version: '2'

services:
  node:
    build: ./
    restart: always
    ports:
      - "8005:8005"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./env/db:/bitnami